### ISSUE TITLE
index.html to index.php , browserSync error?

### ISSUE THREAD

**Issue by dakicks87** [BlackrockDigital/startbootstrap-freelancer#234]
Hello I have renamed `index.html` to `index.php` , to add php codes to it. However when running `npm start`, the browserSync opens a new browser window with error message 

> Cannot GET /

How do i fixs this?

**Comment by maan** [comment]
Are you looking at Port 3000 or 3001?

**Comment by dakicks87** [comment]
@maan Port 3000

**Comment by davidtmiller** [comment]
Originally, this issue would have happened since you're not rendering out the PHP to anything, and browserSync is meant to watch the HTML files. The scripts have been rewritten and the source files of the theme now use Pug - so this issue would no longer apply since renaming Pug files to PHP will not be supported in v6 and on.
