### ISSUE TITLE
Netlify mail form

### ISSUE THREAD

**Issue by shaka0241** [BlackrockDigital/startbootstrap-freelancer#246]
Hello! help!

I uploaded my startbootstrap-freelancer project to netlify and sending it to the email via form throws me an error. I add the tags data-netlify = "true" // data-netlify-recaptcha = "true".

Anyone with the family problem that has solved it?

I leave error image
![image](https://user-images.githubusercontent.com/25334358/71622144-8db76180-2bb2-11ea-9b70-4a178b0cbd8c.png)

![image](https://user-images.githubusercontent.com/25334358/71622157-a58ee580-2bb2-11ea-876c-9e1ffd924a9f.png)

**Comment by shaka0241** [comment]
@davidtmiller

**Comment by EliottGdl** [comment]
Hello, did you resolve your problem or not ? Because I actually have the same

**Comment by shaka0241** [comment]
> Hello, did you resolve your problem or not ? Because I actually have the same


That's right, I still have it. What I did was take an example of a form in the netlify documentation and put classes on the theme you are using (bootstrap). You understand me ?

**Comment by EliottGdl** [comment]
Yes I did pretty much the same but I don't understand why it doesn't work, if you have any ideas tell me !

**Comment by shaka0241** [comment]
> Yes I did pretty much the same but I don't understand why it doesn't work, if you have any ideas tell me !

My teacher told me that apparently he could solve that problem, but I could not do it correctly. You can consult him @dieg0

**Comment by davidtmiller** [comment]
Here is a post from StackOverflow that did a really great job troubleshooting any problems that may arise on one of these contact forms: https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail

I have future plants to explore a different means of getting the contact form up and running, but there are a lot of things to consider when making even a basic contact form, so it's going to be a while before anything comes out.

That being said, hopefully that post helps you out. Since this is a many-times duplicated issue to some degree I am going to close it for now.
